# Generated by Django 5.1.3 on 2024-12-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0002_rename_reader_department_author_author_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_title',
            field=models.TextField(default='Untitled'),
        ),
    ]
