# Generated by Django 5.1.3 on 2024-12-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0003_author_author_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='active',
        ),
    ]
