# Generated by Django 5.1.3 on 2024-12-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0004_remove_author_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='employee_number',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
