# Generated by Django 5.1.3 on 2024-12-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0005_author_employee_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('date_started', models.DateField()),
                ('researchers', models.TextField()),
            ],
        ),
    ]
