# Generated by Django 5.1.3 on 2024-12-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0006_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='study',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='rms_app.author'),
        ),
        migrations.AddField(
            model_name='study',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='studies/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='employee_number',
            field=models.CharField(max_length=100),
        ),
    ]
